<?php
/**
 * Array of settings to be installed with package.
 *
 * Returns an array of meta information for setting for the package. Each setting
 * should be an array containing 'key', 'value', 'xtype', 'namespace', and 'area'.
 *
 * Example:
 * return array(
 *     array(
 *         'key' => 'packagename.setting_name',
 *         'value' => '',
 *         'xtype' => 'textfield',
 *         'namespace' => 'packagename',
 *         'area' => 'general'
 *     ),
 *     array(
 *         'key' => 'packagename.setting2_name',
 *         'value' => 'myValue',
 *         'xtype' => 'textfield',
 *         'namespace' => 'packagename',
 *         'area' => 'general'
 *     )
 * );
 *
 * @package phpThumbsUp
 * @subpackage TransportBuilder
 */

return array(
    array(
        'key' => 'phpthumbsup.core_path',
        'value' => '{core_path}components/phpthumbsup/',
        'xtype' => 'textfield',
        'namespace' => 'phpthumbsup',
        'area' => 'paths',
		'description' => 'The path to the phpThumbsUp component.'
    ),
    array(
        'key' => 'phpthumbsup.cache_path',
        'value' => '{core_path}components/phpthumbsup/cache/',
        'xtype' => 'textfield',
        'namespace' => 'phpthumbsup',
        'area' => 'paths',
		'description' => 'The path to the cache directory where phpThumbsUp stores image files.',
    ),
    array(
        'key' => 'phpthumbsup.base_url',
        'value' => 'phpthumbsup/',
        'xtype' => 'textfield',
        'namespace' => 'phpthumbsup',
        'area' => 'general',
		'description' => 'The base URL for all images generated by phpThumbsUp. This should never be the same as an alias for one of your resources.'
    ),
    array(
        'key' => 'phpthumbsup.auto_create',
        'value' => '',
        'xtype' => 'textfield',
        'namespace' => 'phpthumbsup',
        'area' => 'general',
		'description' => 'Enter one or more colon-separated paths to create thumbs automatically when an image is uploaded through the MODX manager. Example: /w/100/h/100/zc/1/src/assets/images/photos/'
    ),
    array(
		'key' => 'phpthumbsup.clear_cache',
		'value' => true,
		'xtype' => 'combo-boolean',
		'namespace' => 'phpthumbsup',
		'area' => 'general',
		'description' => 'If set to true, the phpThumbsUp image cache will be cleared when you clear your MODX cache.'
	),
	array(
		'key' => 'phpthumbsup.available_options',
		'value' => 'w,h,wp,hp,wl,hl,ws,hs,f,q,sx,sy,sw,sh,zc,bg,bc,fltr,xto,ra,ar,sfn,aoe,iar,far,dpi,maxb',
		'xtype' => 'textfield',
		'namespace' => 'phpthumbsup',
		'area' => 'general',
		'description' => 'A comma-separated list of options that phpThumbsUp will recognize and process (see http://phpthumb.sourceforge.net/demo/docs/phpthumb.readme.txt for a full list of options)'
	),
	array(
		'key' => 'phpthumbsup.available_filters',
		'value' => 'brit,cont,gam,sat,ds,gray,th,rcd,clr,sep,usm,blur,sblr,smth,lvl,wb,hist,flip,ric,elip,bvl,bord,fram,drop,crop,rot,size,stc',
		'xtype' => 'textfield',
		'namespace' => 'phpthumbsup',
		'area' => 'general',
		'description' => 'A comma-separated list of filters (fltr[]) that phpThumbsUp will recognize and process (see http://phpthumb.sourceforge.net/demo/docs/phpthumb.readme.txt for a full list of filters)'
	)
);