<?php
/**
 * Language file for phpThumbsUp.
 *
 * @package phpThumbsUp
 */

$_lang['setting_phpthumbsup.core_path'] = 'Core Path';
$_lang['setting_phpthumbsup.core_path_desc'] = 'The path to the phpThumbsUp component. DO NOT change this unless you have a custom MODX installation.';

$_lang['setting_phpthumbsup.cache_path'] = 'Cache Path';
$_lang['setting_phpthumbsup.cache_path_desc'] = 'The path to the cache directory where phpThumbsUp stores image files.';

$_lang['setting_phpthumbsup.base_url'] = 'Base URL';
$_lang['setting_phpthumbsup.base_url_desc'] = 'The base URL for all images generated by phpThumbsUp. This should never be the same as an alias for one of your resources.';

$_lang['setting_phpthumbsup.auto_create'] = 'Auto Create';
$_lang['setting_phpthumbsup.auto_create_desc'] = 'Enter one or more colon-separated paths to create thumbs automatically when an image is uploaded through the MODX manager. Example: /w/100/h/100/zc/1/src/assets/images/photos:/w400/src/assets/images';

$_lang['setting_phpthumbsup.clear_cache'] = 'Clear Cache';
$_lang['setting_phpthumbsup.clear_cache_desc'] = 'If set to yes, the phpThumbsUp image cache will be cleared when you clear your site cache.';

$_lang['setting_phpthumbsup.available_options'] = 'Available Options';
$_lang['setting_phpthumbsup.available_options_desc'] = 'A comma-separated list of options that phpThumbsUp will recognize and process (see http://phpthumb.sourceforge.net/demo/docs/phpthumb.readme.txt for a full list of options).';

$_lang['setting_phpthumbsup.available_filters'] = 'Available Filters';
$_lang['setting_phpthumbsup.available_filters_desc'] = 'A comma-separated list of filters (fltr[]) that phpThumbsUp will recognize and process (see http://phpthumb.sourceforge.net/demo/docs/phpthumb.readme.txt for a full list of filters)';